#!/usr/bin/env bash

TF_ENV=$1   # staging, production, etc
TF_STATE=$2 # network, data, compute

ALL_ARGS=("$@")
REST_ARGS=("${ALL_ARGS[@]:3}")

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Always run from the location of this script
cd "$DIR" || exit

if [ $# -gt 0 ]; then

  if [ ! -d "$TF_ENV/$TF_STATE" ]; then
    echo >&2 "Directory $DIR/$TF_ENV/$TF_STATE" does not exist
    exit 1
  fi

  if [ "$3" == "init" ]; then
    terraform -chdir=./"$TF_ENV"/"$TF_STATE" init "${REST_ARGS[@]}"
    # -backend-config="bucket=terraform-practice" \
    # -backend-config="key=$TF_ENV/$TF_STATE.tfstate"
  else
    terraform -chdir=./"$TF_ENV"/"$TF_STATE" "$3" "${REST_ARGS[@]}"
  fi
fi
# Head back to original location to avoid surprises
cd - || exit
