#!/usr/bin/env bash

# Usage:
# ./run.sh staging init
# ./run.sh staging plan
# ./run.sh staging apply
# What it does is: terraform -chdir=./staging init -backend-config=../backend-staging.tf

TF_ENV=$1 # staging, production, etc
ALL_ARGS=("$@")
REST_ARGS=("${ALL_ARGS[@]:2}")

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Always run from the location of this script
cd "$DIR" || exit

if [ $# -gt 0 ]; then
  if [ "$2" == "init" ]; then
    terraform -chdir=./"$TF_ENV" init -backend-config=../backend-"$TF_ENV".tf "${REST_ARGS[@]}"
  else
    terraform -chdir=./"$TF_ENV" "$2" "${REST_ARGS[@]}"
  fi
fi

# Head back to original location to avoid surprises
cd - || exit
